username: test      # Username here

# Static User Information
maximum_parallel_level: 3
maximum_stop_level: 10
GPU_allowence: True
max_qubits_in_cpu: 25
max_qubits_in_gpu: 25

# Dynamic User Information
number_of_running_jobs: 0
number_of_stop_jobs: 0
running_qubits_in_cpu: 0
running_qubits_in_gpu: 0
