site_name: QuICT

nav:
- 概览: home.md
- 安装: installation.md
- 功能模块:
  - 算法: functions/algorithms.md
  - 核心: functions/core.md
  - 量子比特: functions/qubit.md
  - 量子门: functions/gates.md
  - 量子电路: functions/circuit.md
  - 噪声模拟: functions/noise.md
  - 布局: functions/layout.md
  - QCDA: functions/qcda.md
  - 量子模拟: functions/simulation.md
  - 工具: functions/tools.md
- 教程:
  - 算法:
    - 经典量子算法:
      - 格罗弗算法: tutorials/algorithm/quantum_algorithm/grover.md
      - 秀尔算法: tutorials/algorithm/quantum_algorithm/shor.md
      - 量子振幅估计: tutorials/algorithm/quantum_algorithm/amplitude_estimate.md
      - 量子游走: tutorials/algorithm/quantum_algorithm/quantum_walk.md
    - 变分量子算法:
      - 量子近似优化算法: tutorials/algorithm/VQA/QAOA.md
      - 量子神经网络: tutorials/algorithm/VQA/QNN.md
      - 变分量子本征求解器: tutorials/algorithm/VQA/VQE.md
  - QCDA:
    - 映射:
      - SABRE映射算法: tutorials/QCDA/mapping/SABRE.md
    - 优化:
      -  Clifford+Rz优化: tutorials/QCDA/optimization/clifford_rz_optimization.md
      -  模板优化: tutorials/QCDA/optimization/template_optimization.md
    - 合成: tutorials/QCDA/synthesis.md
  - 量子电路: tutorials/quantum_circuit.md
- API:
  - Algorithm:
    - Quantum Machine Learning:
      - QAOA: API_qaoa.md
- Benchmark: benchmark.md
- Contribution: contribution.md
    
theme:
  name: material
  logo: assets/images/logos/logo.png
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - toc.follow
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/git-alt
  palette: 
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: QuICT
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/style.css

extra:
  # alternate:
  #   - name: Chinese (Simplified)
  #     link: 
  #     lang: zh
  #   - name: English
  #     link: /en/
  #     lang: en
  # version:
  #   provider: mike
  generator: false

repo_name: QuICT
repo_url: https://e.gitee.com/quictucas/repos/quictucas/quict/sources
edit_uri: ""
copyright: Copyright &copy; ICT
plugins:
  - glightbox
  - tags
  - search:
      lang:
        - en
        - jp

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
