site_name: QuICT (预览版)

nav:
- 概览: home.md
- 安装: installation.md
- 功能模块:
  - 量子比特: functions/qubit.md
  - 量子门: functions/gates.md
  - 量子电路: functions/circuit.md
  - 量子噪声: functions/noise.md
  - QCDA:
    - 映射:
      - SABRE映射算法: functions/QCDA/mapping/SABRE.md
      - 基于图学习及强化学习的量子电路映射算法: functions/QCDA/mapping/RL_mapping.md
    - 优化:
      - Clifford+Rz优化: functions/QCDA/optimization/clifford_rz_optimization.md
      - Clifford电路合成与symbolic优化: functions/QCDA/optimization/clifford.md
      - 交换优化: functions/QCDA/optimization/commutative_optimization.md
      - 模板优化: functions/QCDA/optimization/template_optimization.md
    - 合成:
      - 门转换: functions/QCDA/synthesis/gate_transform.md
      - 量子态制备: functions/QCDA/synthesis/quantum_state_preparation.md
      - 酉矩阵分解: functions/QCDA/synthesis/unitary_decomposition.md
  - 量子模拟: functions/simulation.md
  - 工具: functions/tools.md
  - 量子物理机基准测试: functions/Machinebenchmark.md
- 教程:
  - 量子电路: tutorials/quantum_circuit.md
  - QCDA: tutorials/QCDA.md
  - 算法:
    - 经典量子算法:
      - Grover搜索算法: tutorials/algorithm/quantum_algorithm/grover.md
      - Shor算法: tutorials/algorithm/quantum_algorithm/shor.md
      - 量子振幅估计: tutorials/algorithm/quantum_algorithm/amplitude_estimate.md
      - 量子游走: tutorials/algorithm/quantum_algorithm/quantum_walk.md
    - 变分量子算法:
      - 变分量子本征求解器: tutorials/algorithm/VQA/VQE.md
      - 量子近似优化算法: tutorials/algorithm/VQA/QAOA.md
      - 量子神经网络: tutorials/algorithm/VQA/QNN.md
- API:
  - Algorithm:
    - Quantum Machine Learning:
      - QAOA: API_qaoa.md
- 基准测试:
  - 简介: QuICTbenchmark/QuICTbenchmark.md
  - 模拟基准测试: QuICTbenchmark/simulation_benchmark.md
  - 算法基准测试: QuICTbenchmark/algorithm_benchmark.md
  - QCDA基准测试: QuICTbenchmark/qcda_benchmark.md
- 贡献: contribution.md
    
theme:
  name: material
  logo: assets/images/logos/logo.png
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - toc.follow
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/git-alt
  palette: 
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: QuICT
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/style.css

extra:
  # alternate:
  #   - name: Chinese (Simplified)
  #     link: 
  #     lang: zh
  #   - name: English
  #     link: /en/
  #     lang: en
  # version:
  #   provider: mike
  generator: false

repo_name: QuICT
repo_url: https://e.gitee.com/quictucas/repos/quictucas/quict/sources
edit_uri: ""
copyright: Copyright &copy; ICT
plugins:
  - glightbox
  - tags
  - search:
      lang:
        - en
        - jp

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
