from .baidu_CloudIoPCAS import BaiduCloudIoPCAS
from .ctek_ClosedBetaQC import CTEKClosedBetaQC
from .ctek_oneD12 import CTEKOneD12
from .ibm_Egret_r1 import IBMEgretR1
from .ibm_Falcon_r4P import IBMFalconr4p
from .ibm_Falcon_r4T import IBMFalconr4T
from .ibm_Falcon_r511 import IBMFalconr511
from .ibm_Falcon_r511H import IBMFalconr511H
from .ibm_Falcon_r511L import IBMFalconr511L
from .ibm_Hummingbird_r3 import IBMHummingbirdr3
from .original_KF_C6_130 import OriginalKFC6130
from .original_KF_C6_131 import OriginalKFC6131
from .quafu_scqp10 import QuafuScQP10
from .quafu_scqp18 import QuafuScQP18
