# CPU simulator

# GPU simulator
GPU:
  # based config
  precision: 1
  gpu_device_id: 0
  sync: False

  statevector: 
    optimize: False

  # Multi-GPU simulator
  multiGPU:
    proxy: 1

Remote:
  token: 1
