# CPU simulator
CPU:
  unitary:
    precision: double

  statevector:
    precision: double

  density_matrix:
    precision: double

# GPU simulator
GPU:
  unitary:
    precision: double

  statevector:
    precision: double
    gpu_device_id: 0
    optimization: False
    matrix_aggregation: True
    sync: True

  density_matrix:
    precision: double

qiskit:
  token: 1

qcompute:
  token: 1
