# CPU simulator

# GPU simulator
GPU:
  unitary:
    precision: 1

  statevector:
    precision: 1
    gpu_device_id: 0
    sync: False
    optimize: False

  multiGPU:
    precision: 1
    gpu_device_id: 0
    sync: False
    proxy: 1

Qiskit:
  token: 1

QCompute:
  token: 1
