# CPU simulator
CPU:
  unitary:
    precision: double
  statevector:
    precision: double

# GPU simulator
GPU:
  unitary:
    precision: double

  statevector:
    precision: double
    gpu_device_id: 0
    sync: True
    optimize: False

qiskit:
  token: 1

qcompute:
  token: 1
